"""Domain contracts for clean architecture boundaries.

All engines depend on these abstractions instead of concrete implementations.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Protocol


@dataclass
class ContextSnapshot:
    """Structured environment understanding used for planning."""

    current_application: str
    user_activity: str
    time_of_day: str
    signals: Dict[str, Any] = field(default_factory=dict)


@dataclass
class PlanStep:
    """One executable action in a plan."""

    id: str
    description: str
    agent_role: str
    skill_name: str


@dataclass
class ExecutionPlan:
    """Planner output consumed by the orchestrator."""

    goal: str
    steps: List[PlanStep]


@dataclass
class StepResult:
    """Execution result for one plan step."""

    step_id: str
    success: bool
    output: str


@dataclass
class OrchestrationReport:
    """Final report generated by the orchestrator."""

    goal: str
    step_results: List[StepResult]


class ContextProvider(Protocol):
    def collect(self) -> ContextSnapshot:
        """Collect and return current context."""


class Planner(Protocol):
    def build_plan(self, goal: str, context: ContextSnapshot) -> ExecutionPlan:
        """Create a plan for the goal using current context."""


class SkillExecutor(Protocol):
    def execute_skill(self, skill_name: str, payload: Dict[str, Any]) -> str:
        """Execute a skill by name and return a textual result."""


class MemoryStore(Protocol):
    def save(self, key: str, value: Dict[str, Any]) -> None:
        """Persist data into memory."""

    def get(self, key: str) -> Dict[str, Any] | None:
        """Retrieve memory data by key."""
